#Requires -Version 7.0

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

foreach ($file in Get-ChildItem -LiteralPath $PSScriptRoot/Private, $PSScriptRoot/Public -Filter *.ps1) {
    . $file.FullName
}

Export-ModuleMember -Function @(
    'Add-GitHubDeployKey'
    'Add-GitHubPullRequestComment'
    'Add-GitHubReleaseAsset'
    'Close-GitHubPullRequest'
    'Connect-GitHubAccount'
    'Copy-GitHubLabel'
    'Disable-GitHubWorkflow'
    'Disconnect-GitHubAccount'
    'Enable-GitHubWorkflow'
    'Get-GitHubAuthStatus'
    'Get-GitHubDefaultRepository'
    'Get-GitHubDeployKey'
    'Get-GitHubLabel'
    'Get-GitHubPullRequest'
    'Get-GitHubPullRequestCheck'
    'Get-GitHubPullRequestDiff'
    'Get-GitHubPullRequestStatus'
    'Get-GitHubRelease'
    'Get-GitHubRepository'
    'Get-GitHubSecret'
    'Get-GitHubToken'
    'Get-GitHubVariable'
    'Get-GitHubWorkflow'
    'Get-GitHubWorkflowRun'
    'Get-GitHubWorkflowRunLog'
    'Invoke-GitHubApi'
    'Lock-GitHubPullRequest'
    'Merge-GitHubPullRequest'
    'New-GitHubFork'
    'New-GitHubLabel'
    'New-GitHubPullRequest'
    'New-GitHubRelease'
    'New-GitHubRepository'
    'Open-GitHubPullRequest'
    'Register-GitHubCredentialHelper'
    'Remove-GitHubDeployKey'
    'Remove-GitHubLabel'
    'Remove-GitHubRelease'
    'Remove-GitHubReleaseAsset'
    'Remove-GitHubRepository'
    'Remove-GitHubSecret'
    'Remove-GitHubVariable'
    'Remove-GitHubWorkflowRun'
    'Rename-GitHubRepository'
    'Restart-GitHubWorkflowRun'
    'Save-GitHubReleaseAsset'
    'Save-GitHubWorkflowRunArtifact'
    'Set-GitHubDefaultRepository'
    'Set-GitHubLabel'
    'Set-GitHubPullRequest'
    'Set-GitHubRelease'
    'Set-GitHubRepository'
    'Set-GitHubSecret'
    'Set-GitHubVariable'
    'Start-GitHubWorkflow'
    'Stop-GitHubWorkflowRun'
    'Submit-GitHubPullRequestReview'
    'Switch-GitHubAccount'
    'Switch-GitHubPullRequest'
    'Sync-GitHubRepository'
    'Test-GitHubApi'
    'Unlock-GitHubPullRequest'
    'Update-GitHubPullRequestBranch'
    'Wait-GitHubWorkflowRun'
)
